id: I0D61A2B8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:42:27+00:00'
last_modified: '2022-06-07T11:36:19.496844+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2KG210295
  title: བཀའ་འགྱུར། ༼ཕུག་བྲག་བྲིས་མ༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    D1FF:
      image_group_id: I2KG210405
      title: ''
      total_pages: 0
      order: 1
      base_file: D1FF.txt
    2DDD:
      image_group_id: I2KG210406
      title: ''
      total_pages: 0
      order: 2
      base_file: 2DDD.txt
    0C6D:
      image_group_id: I2KG210407
      title: ''
      total_pages: 0
      order: 3
      base_file: 0C6D.txt
    2D7C:
      image_group_id: I2KG210408
      title: ''
      total_pages: 0
      order: 4
      base_file: 2D7C.txt
    A0CC:
      image_group_id: I2KG210409
      title: ''
      total_pages: 0
      order: 5
      base_file: A0CC.txt
    B558:
      image_group_id: I2KG210410
      title: ''
      total_pages: 0
      order: 6
      base_file: B558.txt
    B6B3:
      image_group_id: I2KG210411
      title: ''
      total_pages: 0
      order: 7
      base_file: B6B3.txt
    F7D5:
      image_group_id: I2KG210412
      title: ''
      total_pages: 0
      order: 8
      base_file: F7D5.txt
    FEEF:
      image_group_id: I2KG210413
      title: ''
      total_pages: 0
      order: 9
      base_file: FEEF.txt
    '9683':
      image_group_id: I2KG210414
      title: ''
      total_pages: 0
      order: 10
      base_file: 9683.txt
    '6156':
      image_group_id: I2KG210415
      title: ''
      total_pages: 0
      order: 11
      base_file: 6156.txt
    9B1F:
      image_group_id: I2KG210416
      title: ''
      total_pages: 0
      order: 12
      base_file: 9B1F.txt
    998B:
      image_group_id: I2KG210417
      title: ''
      total_pages: 0
      order: 13
      base_file: 998B.txt
    '0125':
      image_group_id: I2KG210418
      title: ''
      total_pages: 0
      order: 14
      base_file: 0125.txt
    '9099':
      image_group_id: I2KG210419
      title: ''
      total_pages: 0
      order: 15
      base_file: 9099.txt
    EAAA:
      image_group_id: I2KG210420
      title: ''
      total_pages: 0
      order: 16
      base_file: EAAA.txt
    '8530':
      image_group_id: I2KG210421
      title: ''
      total_pages: 0
      order: 17
      base_file: 8530.txt
    9CC7:
      image_group_id: I2KG210422
      title: ''
      total_pages: 0
      order: 18
      base_file: 9CC7.txt
    F30B:
      image_group_id: I2KG210423
      title: ''
      total_pages: 0
      order: 19
      base_file: F30B.txt
    D0A1:
      image_group_id: I2KG210424
      title: ''
      total_pages: 0
      order: 20
      base_file: D0A1.txt
    F810:
      image_group_id: I2KG210425
      title: ''
      total_pages: 0
      order: 21
      base_file: F810.txt
    0C90:
      image_group_id: I2KG210426
      title: ''
      total_pages: 0
      order: 22
      base_file: 0C90.txt
    99CE:
      image_group_id: I2KG210427
      title: ''
      total_pages: 0
      order: 23
      base_file: 99CE.txt
    7EAA:
      image_group_id: I2KG210428
      title: ''
      total_pages: 0
      order: 24
      base_file: 7EAA.txt
    3C5A:
      image_group_id: I2KG210429
      title: ''
      total_pages: 0
      order: 25
      base_file: 3C5A.txt
    B804:
      image_group_id: I2KG210430
      title: ''
      total_pages: 0
      order: 26
      base_file: B804.txt
    '4770':
      image_group_id: I2KG210431
      title: ''
      total_pages: 0
      order: 27
      base_file: 4770.txt
    38CE:
      image_group_id: I2KG210432
      title: ''
      total_pages: 0
      order: 28
      base_file: 38CE.txt
    4CAF:
      image_group_id: I2KG210433
      title: ''
      total_pages: 0
      order: 29
      base_file: 4CAF.txt
    DB2B:
      image_group_id: I2KG210434
      title: ''
      total_pages: 0
      order: 30
      base_file: DB2B.txt
    '9225':
      image_group_id: I2KG210435
      title: ''
      total_pages: 0
      order: 31
      base_file: 9225.txt
    DA84:
      image_group_id: I2KG210436
      title: ''
      total_pages: 0
      order: 32
      base_file: DA84.txt
    DE2A:
      image_group_id: I2KG210437
      title: ''
      total_pages: 0
      order: 33
      base_file: DE2A.txt
    FFD7:
      image_group_id: I2KG210438
      title: ''
      total_pages: 0
      order: 34
      base_file: FFD7.txt
    '3944':
      image_group_id: I2KG210439
      title: ''
      total_pages: 0
      order: 35
      base_file: 3944.txt
    F887:
      image_group_id: I2KG210440
      title: ''
      total_pages: 0
      order: 36
      base_file: F887.txt
    5ECA:
      image_group_id: I2KG210441
      title: ''
      total_pages: 0
      order: 37
      base_file: 5ECA.txt
    27DC:
      image_group_id: I2KG210442
      title: ''
      total_pages: 0
      order: 38
      base_file: 27DC.txt
    30B3:
      image_group_id: I2KG210443
      title: ''
      total_pages: 0
      order: 39
      base_file: 30B3.txt
    '8154':
      image_group_id: I2KG210444
      title: ''
      total_pages: 0
      order: 40
      base_file: 8154.txt
    8B3F:
      image_group_id: I2KG210445
      title: ''
      total_pages: 0
      order: 41
      base_file: 8B3F.txt
    5EE5:
      image_group_id: I2KG210446
      title: ''
      total_pages: 0
      order: 42
      base_file: 5EE5.txt
    '5607':
      image_group_id: I2KG210447
      title: ''
      total_pages: 0
      order: 43
      base_file: 5607.txt
    2A3A:
      image_group_id: I2KG210448
      title: ''
      total_pages: 0
      order: 44
      base_file: 2A3A.txt
    '8562':
      image_group_id: I2KG210449
      title: ''
      total_pages: 0
      order: 45
      base_file: 8562.txt
    DF75:
      image_group_id: I2KG210450
      title: ''
      total_pages: 0
      order: 46
      base_file: DF75.txt
    018E:
      image_group_id: I2KG210451
      title: ''
      total_pages: 0
      order: 47
      base_file: 018E.txt
    6AEF:
      image_group_id: I2KG210452
      title: ''
      total_pages: 0
      order: 48
      base_file: 6AEF.txt
    75BC:
      image_group_id: I2KG210453
      title: ''
      total_pages: 0
      order: 49
      base_file: 75BC.txt
    '9668':
      image_group_id: I2KG210454
      title: ''
      total_pages: 0
      order: 50
      base_file: 9668.txt
    B442:
      image_group_id: I2KG210455
      title: ''
      total_pages: 0
      order: 51
      base_file: B442.txt
    CDF9:
      image_group_id: I2KG210456
      title: ''
      total_pages: 0
      order: 52
      base_file: CDF9.txt
    43FB:
      image_group_id: I2KG210457
      title: ''
      total_pages: 0
      order: 53
      base_file: 43FB.txt
    B746:
      image_group_id: I2KG210458
      title: ''
      total_pages: 0
      order: 54
      base_file: B746.txt
    8F8F:
      image_group_id: I2KG210459
      title: ''
      total_pages: 0
      order: 55
      base_file: 8F8F.txt
    444C:
      image_group_id: I2KG210460
      title: ''
      total_pages: 0
      order: 56
      base_file: 444C.txt
    44AF:
      image_group_id: I2KG210461
      title: ''
      total_pages: 0
      order: 57
      base_file: 44AF.txt
    18B9:
      image_group_id: I2KG210462
      title: ''
      total_pages: 0
      order: 58
      base_file: 18B9.txt
    '5261':
      image_group_id: I2KG210463
      title: ''
      total_pages: 0
      order: 59
      base_file: 5261.txt
    5C0B:
      image_group_id: I2KG210464
      title: ''
      total_pages: 0
      order: 60
      base_file: 5C0B.txt
    7D09:
      image_group_id: I2KG210465
      title: ''
      total_pages: 0
      order: 61
      base_file: 7D09.txt
    CEDC:
      image_group_id: I2KG210466
      title: ''
      total_pages: 0
      order: 62
      base_file: CEDC.txt
    '9024':
      image_group_id: I2KG210499
      title: ''
      total_pages: 0
      order: 95
      base_file: 9024.txt
    '4167':
      image_group_id: I2KG210468
      title: ''
      total_pages: 0
      order: 64
      base_file: 4167.txt
    E7B6:
      image_group_id: I2KG210469
      title: ''
      total_pages: 0
      order: 65
      base_file: E7B6.txt
    '4976':
      image_group_id: I2KG210470
      title: ''
      total_pages: 0
      order: 66
      base_file: 4976.txt
    789B:
      image_group_id: I2KG210471
      title: ''
      total_pages: 0
      order: 67
      base_file: 789B.txt
    42C4:
      image_group_id: I2KG210472
      title: ''
      total_pages: 0
      order: 68
      base_file: 42C4.txt
    F92E:
      image_group_id: I2KG210473
      title: ''
      total_pages: 0
      order: 69
      base_file: F92E.txt
    F7FF:
      image_group_id: I2KG210474
      title: ''
      total_pages: 0
      order: 70
      base_file: F7FF.txt
    A16C:
      image_group_id: I2KG210475
      title: ''
      total_pages: 0
      order: 71
      base_file: A16C.txt
    00AA:
      image_group_id: I2KG210476
      title: ''
      total_pages: 0
      order: 72
      base_file: 00AA.txt
    49D8:
      image_group_id: I2KG210477
      title: ''
      total_pages: 0
      order: 73
      base_file: 49D8.txt
    F807:
      image_group_id: I2KG210478
      title: ''
      total_pages: 0
      order: 74
      base_file: F807.txt
    D776:
      image_group_id: I2KG210479
      title: ''
      total_pages: 0
      order: 75
      base_file: D776.txt
    67E7:
      image_group_id: I2KG210480
      title: ''
      total_pages: 0
      order: 76
      base_file: 67E7.txt
    BB5D:
      image_group_id: I2KG210481
      title: ''
      total_pages: 0
      order: 77
      base_file: BB5D.txt
    2C42:
      image_group_id: I2KG210482
      title: ''
      total_pages: 0
      order: 78
      base_file: 2C42.txt
    '6767':
      image_group_id: I2KG210483
      title: ''
      total_pages: 0
      order: 79
      base_file: 6767.txt
    ABFF:
      image_group_id: I2KG210484
      title: ''
      total_pages: 0
      order: 80
      base_file: ABFF.txt
    BC84:
      image_group_id: I2KG210485
      title: ''
      total_pages: 0
      order: 81
      base_file: BC84.txt
    18CA:
      image_group_id: I2KG210486
      title: ''
      total_pages: 0
      order: 82
      base_file: 18CA.txt
    92AC:
      image_group_id: I2KG210487
      title: ''
      total_pages: 0
      order: 83
      base_file: 92AC.txt
    D4EE:
      image_group_id: I2KG210488
      title: ''
      total_pages: 0
      order: 84
      base_file: D4EE.txt
    5B0E:
      image_group_id: I2KG210489
      title: ''
      total_pages: 0
      order: 85
      base_file: 5B0E.txt
    A6F4:
      image_group_id: I2KG210490
      title: ''
      total_pages: 0
      order: 86
      base_file: A6F4.txt
    4CFF:
      image_group_id: I2KG210491
      title: ''
      total_pages: 0
      order: 87
      base_file: 4CFF.txt
    2A83:
      image_group_id: I2KG210492
      title: ''
      total_pages: 0
      order: 88
      base_file: 2A83.txt
    F9C7:
      image_group_id: I2KG210493
      title: ''
      total_pages: 0
      order: 89
      base_file: F9C7.txt
    06D9:
      image_group_id: I2KG210494
      title: ''
      total_pages: 0
      order: 90
      base_file: 06D9.txt
    7A9B:
      image_group_id: I2KG210495
      title: ''
      total_pages: 0
      order: 91
      base_file: 7A9B.txt
    210F:
      image_group_id: I2KG210496
      title: ''
      total_pages: 0
      order: 92
      base_file: 210F.txt
    FB1B:
      image_group_id: I2KG210497
      title: ''
      total_pages: 0
      order: 93
      base_file: FB1B.txt
    F9B8:
      image_group_id: I2KG210498
      title: ''
      total_pages: 0
      order: 94
      base_file: F9B8.txt
    437B:
      image_group_id: I2KG210500
      title: ''
      total_pages: 0
      order: 96
      base_file: 437B.txt
    4D93:
      image_group_id: I2KG210501
      title: ''
      total_pages: 0
      order: 97
      base_file: 4D93.txt
    849B:
      image_group_id: I2KG210502
      title: ''
      total_pages: 0
      order: 98
      base_file: 849B.txt
    9E4E:
      image_group_id: I2KG210503
      title: ''
      total_pages: 0
      order: 99
      base_file: 9E4E.txt
    24E7:
      image_group_id: I2KG210504
      title: ''
      total_pages: 0
      order: 100
      base_file: 24E7.txt
    88D0:
      image_group_id: I2KG210505
      title: ''
      total_pages: 0
      order: 101
      base_file: 88D0.txt
    FEB6:
      image_group_id: I2KG210506
      title: ''
      total_pages: 0
      order: 102
      base_file: FEB6.txt
    2E8A:
      image_group_id: I2KG210507
      title: ''
      total_pages: 0
      order: 103
      base_file: 2E8A.txt
    B9A5:
      image_group_id: I2KG210508
      title: ''
      total_pages: 0
      order: 104
      base_file: B9A5.txt
    '0000':
      image_group_id: I2KG210509
      title: ''
      total_pages: 0
      order: 105
      base_file: 0000.txt
    46A5:
      image_group_id: I2KG210510
      title: ''
      total_pages: 0
      order: 106
      base_file: 46A5.txt
    D8E5:
      image_group_id: I2KG210511
      title: ''
      total_pages: 0
      order: 107
      base_file: D8E5.txt
    '1466':
      image_group_id: I2KG210512
      title: ''
      total_pages: 0
      order: 108
      base_file: 1466.txt
    FA42:
      image_group_id: I2KG210513
      title: ''
      total_pages: 0
      order: 109
      base_file: FA42.txt
    B7E8:
      image_group_id: I2KG210514
      title: ''
      total_pages: 0
      order: 110
      base_file: B7E8.txt
    A721:
      image_group_id: I2KG210515
      title: ''
      total_pages: 0
      order: 111
      base_file: A721.txt
    '1157':
      image_group_id: I2KG210516
      title: ''
      total_pages: 0
      order: 112
      base_file: 1157.txt
    E94C:
      image_group_id: I2KG210517
      title: ''
      total_pages: 0
      order: 113
      base_file: E94C.txt
    '4940':
      image_group_id: I2KG210518
      title: ''
      total_pages: 0
      order: 114
      base_file: 4940.txt
    DA95:
      image_group_id: I2KG210519
      title: ''
      total_pages: 0
      order: 115
      base_file: DA95.txt
    7C79:
      image_group_id: I2KG210520
      title: ''
      total_pages: 0
      order: 116
      base_file: 7C79.txt
    7B8B:
      image_group_id: I2KG210521
      title: ''
      total_pages: 0
      order: 117
      base_file: 7B8B.txt
    E6AA:
      image_group_id: I2KG210522
      title: ''
      total_pages: 0
      order: 118
      base_file: E6AA.txt
    D99B:
      image_group_id: I2KG210523
      title: ''
      total_pages: 0
      order: 119
      base_file: D99B.txt
    74A6:
      image_group_id: I2KG210524
      title: ''
      total_pages: 0
      order: 120
      base_file: 74A6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
